name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: LS
        run: ls

      - name: Copy build directory via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
            server: ftp.bisericaava.ro
            username: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            server_dir: /
            local_dir: build
