name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install and build the app
    - run: npm ci
    - run: npm run build --if-present

    - name: Do something else
    - run: echo "hello"
    