name: Deployment pipeline

on:
  push:
    branches:
      - master  # Change to your deployment branch if needed
  workflow_dispatch:  # Allows for manual triggering of the workflow
    inputs:
      dir:  
        description: 'Where to store the build'
        required: true 
        default: 'dev.bisericaava.ro'  

jobs:
  deploy:
    name: Deploy to dev.bisericaava.ro
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies (if needed, e.g., for a Node.js project)
      - name: Install Dependencies
        run: npm ci

      # Build the project (if needed, e.g., for a front-end framework like Vue or React)
      - name: Build Project
        run: npm run build

      # Deploy the dist folder via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}  # Default port is 21, change if necessary
          local-dir: build/                    # Local dist folder to upload
          server-dir: dev.bisericaava.ro/  # Remote directory on the server
          protocol: ftps                       # Change to `ftp` if you're using plain FTP
          # log-level: verbose                   # Log output for debugging purposes
  
  manualDeployment:
    name: Manual Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}  # Run this job only when triggered manually

    steps:
      # Checkout the latest code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build the project
      - name: Build Project
        run: npm run build

      # Deploy the build folder via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}  # Default port is 21, change if necessary
          local-dir: build/                    # Local build folder to upload
          server-dir: ${{ github.event.inputs.dir }}  # Use the manual input for server directory
          protocol: ftps                       # Change to `ftp` if you're using plain FTP
          # log-level: verbose                   # Log output for debugging purposes